theme: jekyll-theme-dinky
title: Projects in Digital Humanities
email: phil.reed@manchester.ac.uk
description: Projects by Phil Reed at The University of Manchester
twitter_username: PhilReedData
github_username: PhilReedData
gems:
  - jemoji